/*
Copyright 2022 The kubeall.com Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package v1alpha1

// This file contains a collection of methods that can be used from go-restful to
// generate Swagger API documentation for its models. Please read this PR for more
// information on the implementation: https://github.com/emicklei/go-restful/pull/215
//
// TODOs are ignored from the parser (e.g. TODO(andronat):... || TODO:...) if and only if
// they are on one line! For multiple line or blocks that you want to ignore use ---.
// Any context after a --- is ignored.
//
// Those methods can be generated by using hack/update-generated-swagger-docs.sh

// AUTO-GENERATED FUNCTIONS START HERE
var map_AliyunACK = map[string]string{
	"": "AliyunACK is the schema for the clusters API",
}

func (AliyunACK) SwaggerDoc() map[string]string {
	return map_AliyunACK
}

var map_AliyunACKStatus = map[string]string{
	"cluster_id": "cluster id",
	"config":     "cluster kubeconfig",
	"expiration": "kubeconfig expire time, format:RFC3339 UTC",
	"tasks":      "all cluster tasks",
}

func (AliyunACKStatus) SwaggerDoc() map[string]string {
	return map_AliyunACKStatus
}

var map_AliyunTask = map[string]string{
	"time":       "request time",
	"request_id": "aliyun response request_id",
	"task_id":    "aliyun response task_id",
}

func (AliyunTask) SwaggerDoc() map[string]string {
	return map_AliyunTask
}

var map_Ask = map[string]string{
	"cluster_type": "集群类型。可选值为ManagedKubernetes，同时profile配置为Serverless，表示创建Serverless集群。",
	"profile":      "集群标识。参数cluster_type取值为ManagedKubernetes，同时该参数配置为Serverless，表示创建Serverless集群。",
	"region_id":    "集群所在的地域ID",
}

func (Ask) SwaggerDoc() map[string]string {
	return map_Ask
}

// AUTO-GENERATED FUNCTIONS END HERE
