/*
Copyright 2022 The kubeall.com Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	tencentv1alpha1 "github.com/kube-all/public-cloud/api/tencent/v1alpha1"
	versioned "github.com/kube-all/public-cloud/client-go/tencent/clientset/versioned"
	internalinterfaces "github.com/kube-all/public-cloud/client-go/tencent/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/kube-all/public-cloud/client-go/tencent/listers/tencent/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// TencentClusterInformer provides access to a shared informer and lister for
// TencentClusters.
type TencentClusterInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.TencentClusterLister
}

type tencentClusterInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewTencentClusterInformer constructs a new informer for TencentCluster type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTencentClusterInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredTencentClusterInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredTencentClusterInformer constructs a new informer for TencentCluster type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredTencentClusterInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.TencentV1alpha1().TencentClusters().List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.TencentV1alpha1().TencentClusters().Watch(context.TODO(), options)
			},
		},
		&tencentv1alpha1.TencentCluster{},
		resyncPeriod,
		indexers,
	)
}

func (f *tencentClusterInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredTencentClusterInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *tencentClusterInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&tencentv1alpha1.TencentCluster{}, f.defaultInformer)
}

func (f *tencentClusterInformer) Lister() v1alpha1.TencentClusterLister {
	return v1alpha1.NewTencentClusterLister(f.Informer().GetIndexer())
}
