/*
Copyright 2022 The kubeall.com Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/kube-all/public-cloud/api/tencent/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAliyunACKs implements AliyunACKInterface
type FakeAliyunACKs struct {
	Fake *FakeTencentV1alpha1
}

var aliyunacksResource = schema.GroupVersionResource{Group: "tencent.kubeall.com", Version: "v1alpha1", Resource: "aliyunacks"}

var aliyunacksKind = schema.GroupVersionKind{Group: "tencent.kubeall.com", Version: "v1alpha1", Kind: "AliyunACK"}

// Get takes name of the aliyunACK, and returns the corresponding aliyunACK object, and an error if there is any.
func (c *FakeAliyunACKs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.AliyunACK, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(aliyunacksResource, name), &v1alpha1.AliyunACK{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AliyunACK), err
}

// List takes label and field selectors, and returns the list of AliyunACKs that match those selectors.
func (c *FakeAliyunACKs) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.AliyunACKList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(aliyunacksResource, aliyunacksKind, opts), &v1alpha1.AliyunACKList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.AliyunACKList{ListMeta: obj.(*v1alpha1.AliyunACKList).ListMeta}
	for _, item := range obj.(*v1alpha1.AliyunACKList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested aliyunACKs.
func (c *FakeAliyunACKs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(aliyunacksResource, opts))
}

// Create takes the representation of a aliyunACK and creates it.  Returns the server's representation of the aliyunACK, and an error, if there is any.
func (c *FakeAliyunACKs) Create(ctx context.Context, aliyunACK *v1alpha1.AliyunACK, opts v1.CreateOptions) (result *v1alpha1.AliyunACK, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(aliyunacksResource, aliyunACK), &v1alpha1.AliyunACK{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AliyunACK), err
}

// Update takes the representation of a aliyunACK and updates it. Returns the server's representation of the aliyunACK, and an error, if there is any.
func (c *FakeAliyunACKs) Update(ctx context.Context, aliyunACK *v1alpha1.AliyunACK, opts v1.UpdateOptions) (result *v1alpha1.AliyunACK, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(aliyunacksResource, aliyunACK), &v1alpha1.AliyunACK{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AliyunACK), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeAliyunACKs) UpdateStatus(ctx context.Context, aliyunACK *v1alpha1.AliyunACK, opts v1.UpdateOptions) (*v1alpha1.AliyunACK, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(aliyunacksResource, "status", aliyunACK), &v1alpha1.AliyunACK{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AliyunACK), err
}

// Delete takes name of the aliyunACK and deletes it. Returns an error if one occurs.
func (c *FakeAliyunACKs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(aliyunacksResource, name, opts), &v1alpha1.AliyunACK{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAliyunACKs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(aliyunacksResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.AliyunACKList{})
	return err
}

// Patch applies the patch and returns the patched aliyunACK.
func (c *FakeAliyunACKs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.AliyunACK, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(aliyunacksResource, name, pt, data, subresources...), &v1alpha1.AliyunACK{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AliyunACK), err
}
