/*
Copyright 2022 The kubeall.com Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/kube-all/public-cloud/api/tencent/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeTencentClusters implements TencentClusterInterface
type FakeTencentClusters struct {
	Fake *FakeTencentV1alpha1
}

var tencentclustersResource = schema.GroupVersionResource{Group: "tencent.kubeall.com", Version: "v1alpha1", Resource: "tencentclusters"}

var tencentclustersKind = schema.GroupVersionKind{Group: "tencent.kubeall.com", Version: "v1alpha1", Kind: "TencentCluster"}

// Get takes name of the tencentCluster, and returns the corresponding tencentCluster object, and an error if there is any.
func (c *FakeTencentClusters) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.TencentCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(tencentclustersResource, name), &v1alpha1.TencentCluster{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TencentCluster), err
}

// List takes label and field selectors, and returns the list of TencentClusters that match those selectors.
func (c *FakeTencentClusters) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.TencentClusterList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(tencentclustersResource, tencentclustersKind, opts), &v1alpha1.TencentClusterList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.TencentClusterList{ListMeta: obj.(*v1alpha1.TencentClusterList).ListMeta}
	for _, item := range obj.(*v1alpha1.TencentClusterList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested tencentClusters.
func (c *FakeTencentClusters) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(tencentclustersResource, opts))
}

// Create takes the representation of a tencentCluster and creates it.  Returns the server's representation of the tencentCluster, and an error, if there is any.
func (c *FakeTencentClusters) Create(ctx context.Context, tencentCluster *v1alpha1.TencentCluster, opts v1.CreateOptions) (result *v1alpha1.TencentCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(tencentclustersResource, tencentCluster), &v1alpha1.TencentCluster{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TencentCluster), err
}

// Update takes the representation of a tencentCluster and updates it. Returns the server's representation of the tencentCluster, and an error, if there is any.
func (c *FakeTencentClusters) Update(ctx context.Context, tencentCluster *v1alpha1.TencentCluster, opts v1.UpdateOptions) (result *v1alpha1.TencentCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(tencentclustersResource, tencentCluster), &v1alpha1.TencentCluster{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TencentCluster), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeTencentClusters) UpdateStatus(ctx context.Context, tencentCluster *v1alpha1.TencentCluster, opts v1.UpdateOptions) (*v1alpha1.TencentCluster, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(tencentclustersResource, "status", tencentCluster), &v1alpha1.TencentCluster{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TencentCluster), err
}

// Delete takes name of the tencentCluster and deletes it. Returns an error if one occurs.
func (c *FakeTencentClusters) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(tencentclustersResource, name, opts), &v1alpha1.TencentCluster{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeTencentClusters) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(tencentclustersResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.TencentClusterList{})
	return err
}

// Patch applies the patch and returns the patched tencentCluster.
func (c *FakeTencentClusters) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.TencentCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(tencentclustersResource, name, pt, data, subresources...), &v1alpha1.TencentCluster{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TencentCluster), err
}
