/*
Copyright 2022 The kubeall.com Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/kube-all/public-cloud/api/tencent/v1alpha1"
	scheme "github.com/kube-all/public-cloud/client-go/tencent/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// TencentClustersGetter has a method to return a TencentClusterInterface.
// A group's client should implement this interface.
type TencentClustersGetter interface {
	TencentClusters() TencentClusterInterface
}

// TencentClusterInterface has methods to work with TencentCluster resources.
type TencentClusterInterface interface {
	Create(ctx context.Context, tencentCluster *v1alpha1.TencentCluster, opts v1.CreateOptions) (*v1alpha1.TencentCluster, error)
	Update(ctx context.Context, tencentCluster *v1alpha1.TencentCluster, opts v1.UpdateOptions) (*v1alpha1.TencentCluster, error)
	UpdateStatus(ctx context.Context, tencentCluster *v1alpha1.TencentCluster, opts v1.UpdateOptions) (*v1alpha1.TencentCluster, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.TencentCluster, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.TencentClusterList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.TencentCluster, err error)
	TencentClusterExpansion
}

// tencentClusters implements TencentClusterInterface
type tencentClusters struct {
	client rest.Interface
}

// newTencentClusters returns a TencentClusters
func newTencentClusters(c *TencentV1alpha1Client) *tencentClusters {
	return &tencentClusters{
		client: c.RESTClient(),
	}
}

// Get takes name of the tencentCluster, and returns the corresponding tencentCluster object, and an error if there is any.
func (c *tencentClusters) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.TencentCluster, err error) {
	result = &v1alpha1.TencentCluster{}
	err = c.client.Get().
		Resource("tencentclusters").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of TencentClusters that match those selectors.
func (c *tencentClusters) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.TencentClusterList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.TencentClusterList{}
	err = c.client.Get().
		Resource("tencentclusters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested tencentClusters.
func (c *tencentClusters) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("tencentclusters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a tencentCluster and creates it.  Returns the server's representation of the tencentCluster, and an error, if there is any.
func (c *tencentClusters) Create(ctx context.Context, tencentCluster *v1alpha1.TencentCluster, opts v1.CreateOptions) (result *v1alpha1.TencentCluster, err error) {
	result = &v1alpha1.TencentCluster{}
	err = c.client.Post().
		Resource("tencentclusters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(tencentCluster).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a tencentCluster and updates it. Returns the server's representation of the tencentCluster, and an error, if there is any.
func (c *tencentClusters) Update(ctx context.Context, tencentCluster *v1alpha1.TencentCluster, opts v1.UpdateOptions) (result *v1alpha1.TencentCluster, err error) {
	result = &v1alpha1.TencentCluster{}
	err = c.client.Put().
		Resource("tencentclusters").
		Name(tencentCluster.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(tencentCluster).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *tencentClusters) UpdateStatus(ctx context.Context, tencentCluster *v1alpha1.TencentCluster, opts v1.UpdateOptions) (result *v1alpha1.TencentCluster, err error) {
	result = &v1alpha1.TencentCluster{}
	err = c.client.Put().
		Resource("tencentclusters").
		Name(tencentCluster.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(tencentCluster).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the tencentCluster and deletes it. Returns an error if one occurs.
func (c *tencentClusters) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("tencentclusters").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *tencentClusters) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("tencentclusters").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched tencentCluster.
func (c *tencentClusters) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.TencentCluster, err error) {
	result = &v1alpha1.TencentCluster{}
	err = c.client.Patch(pt).
		Resource("tencentclusters").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
