/*
Copyright 2022 The kubeall.com Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	aliyunv1alpha1 "github.com/kube-all/public-cloud/api/aliyun/v1alpha1"
	versioned "github.com/kube-all/public-cloud/client-go/aliyun/clientset/versioned"
	internalinterfaces "github.com/kube-all/public-cloud/client-go/aliyun/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/kube-all/public-cloud/client-go/aliyun/listers/aliyun/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// AliyunACKInformer provides access to a shared informer and lister for
// AliyunACKs.
type AliyunACKInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.AliyunACKLister
}

type aliyunACKInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewAliyunACKInformer constructs a new informer for AliyunACK type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewAliyunACKInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredAliyunACKInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredAliyunACKInformer constructs a new informer for AliyunACK type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredAliyunACKInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AliyunV1alpha1().AliyunACKs().List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AliyunV1alpha1().AliyunACKs().Watch(context.TODO(), options)
			},
		},
		&aliyunv1alpha1.AliyunACK{},
		resyncPeriod,
		indexers,
	)
}

func (f *aliyunACKInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredAliyunACKInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *aliyunACKInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&aliyunv1alpha1.AliyunACK{}, f.defaultInformer)
}

func (f *aliyunACKInformer) Lister() v1alpha1.AliyunACKLister {
	return v1alpha1.NewAliyunACKLister(f.Informer().GetIndexer())
}
